### ISSUE TITLE
Request: Add to brew

### ISSUE THREAD

**Issue by joryirving** [mirceanton/talswitcher#53]
I would love to see this available in `brew` similar to `talhelper`.

I found this doc, and rather than do any work myself, leave it to you to close this and ignore it forever:
https://docs.brew.sh/Adding-Software-to-Homebrew

**Comment by mircea-pavel-anton** [comment]
@joryirving In my language we have a saying which roughly translates to "out customer, our master" :))

I'll try to get to it this weekend. I'm a bit busy till then
